<?php

class tx_invalid_name {}

class invalid_Name {}

class invalid_name {}

class Invalid_name {}

class ux_valid_name {}

class user_valid_name {}

class _Invalid_Name {}

interface tx_invalid_name {}

interface invalid_name {}

interface Invalid_name {}

interface _Invalid_Name {}

class ___ {}

interface ___ {}

class Invalid__Name {}

interface Invalid__Name {}


class tx_valid_ClassName {}
class user_valid_ClassName {}
class ux_valid_ClassName {}

interface tx_valid_ClassName {}
?>